CREATE EXTENSION IF NOT EXISTS "pgcrypto";
DO $$ BEGIN CREATE TYPE user_role AS ENUM ('customer','seller','admin'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE payment_status AS ENUM ('pending','paid','failed','cancelled','refunded'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE order_status AS ENUM ('pending','processing','completed','cancelled','refunded'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS users (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), full_name VARCHAR(150) NOT NULL, email VARCHAR(255) UNIQUE NOT NULL, phone VARCHAR(30), password_hash TEXT NOT NULL, role user_role NOT NULL DEFAULT 'customer', is_active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS stores (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), owner_id UUID NOT NULL REFERENCES users(id), name VARCHAR(160) NOT NULL, slug VARCHAR(180) UNIQUE NOT NULL, description TEXT, logo_url TEXT, status VARCHAR(30) NOT NULL DEFAULT 'active', created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS products (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), store_id UUID NOT NULL REFERENCES stores(id), name VARCHAR(200) NOT NULL, description TEXT, price NUMERIC(12,2) NOT NULL CHECK(price>=0), stock INTEGER NOT NULL DEFAULT 0 CHECK(stock>=0), image_url TEXT, status VARCHAR(30) NOT NULL DEFAULT 'active', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS commission_settings (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), store_id UUID UNIQUE REFERENCES stores(id), percentage NUMERIC(5,2) NOT NULL DEFAULT 5 CHECK(percentage>=0), fixed_fee NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK(fixed_fee>=0), active BOOLEAN NOT NULL DEFAULT TRUE, updated_by UUID REFERENCES users(id), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS orders (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), order_number VARCHAR(30) UNIQUE NOT NULL, customer_id UUID NOT NULL REFERENCES users(id), subtotal NUMERIC(12,2) NOT NULL, total NUMERIC(12,2) NOT NULL, currency CHAR(3) NOT NULL DEFAULT 'EGP', status order_status NOT NULL DEFAULT 'pending', payment_status payment_status NOT NULL DEFAULT 'pending', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS order_items (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE, product_id UUID REFERENCES products(id), store_id UUID NOT NULL REFERENCES stores(id), product_name VARCHAR(200) NOT NULL, quantity INTEGER NOT NULL CHECK(quantity>0), unit_price NUMERIC(12,2) NOT NULL, subtotal NUMERIC(12,2) NOT NULL);
CREATE TABLE IF NOT EXISTS payments (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), order_id UUID NOT NULL REFERENCES orders(id), provider VARCHAR(50) NOT NULL, provider_transaction_id VARCHAR(150), provider_reference VARCHAR(150), amount NUMERIC(12,2) NOT NULL, currency CHAR(3) NOT NULL DEFAULT 'EGP', status payment_status NOT NULL DEFAULT 'pending', checkout_url TEXT, raw_response JSONB, paid_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(provider, provider_transaction_id));
CREATE TABLE IF NOT EXISTS commissions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), order_id UUID NOT NULL REFERENCES orders(id), store_id UUID NOT NULL REFERENCES stores(id), rate NUMERIC(5,2) NOT NULL, fixed_fee NUMERIC(12,2) NOT NULL DEFAULT 0, amount NUMERIC(12,2) NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(order_id, store_id));
CREATE TABLE IF NOT EXISTS seller_wallets (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), seller_id UUID UNIQUE NOT NULL REFERENCES users(id), pending_balance NUMERIC(12,2) NOT NULL DEFAULT 0, available_balance NUMERIC(12,2) NOT NULL DEFAULT 0, updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS seller_ledger (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), seller_id UUID NOT NULL REFERENCES users(id), order_id UUID REFERENCES orders(id), payout_id UUID, entry_type VARCHAR(40) NOT NULL, amount NUMERIC(12,2) NOT NULL, balance_after NUMERIC(12,2) NOT NULL, description TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS payouts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), seller_id UUID NOT NULL REFERENCES users(id), amount NUMERIC(12,2) NOT NULL CHECK(amount>0), method VARCHAR(50) NOT NULL, destination JSONB NOT NULL DEFAULT '{}'::jsonb, status VARCHAR(30) NOT NULL DEFAULT 'requested', provider_reference VARCHAR(150), requested_at TIMESTAMPTZ NOT NULL DEFAULT now(), completed_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS refunds (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), order_id UUID NOT NULL REFERENCES orders(id), payment_id UUID REFERENCES payments(id), amount NUMERIC(12,2) NOT NULL CHECK(amount>0), reason TEXT, status VARCHAR(30) NOT NULL DEFAULT 'requested', provider_refund_id VARCHAR(150), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), processed_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS webhook_events (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), provider VARCHAR(50) NOT NULL, event_type VARCHAR(60) NOT NULL, transaction_id VARCHAR(150), signature TEXT, payload JSONB NOT NULL, processed BOOLEAN NOT NULL DEFAULT FALSE, processed_at TIMESTAMPTZ, error_message TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_products_store ON products(store_id); CREATE INDEX IF NOT EXISTS idx_orders_customer ON orders(customer_id); CREATE INDEX IF NOT EXISTS idx_items_order ON order_items(order_id); CREATE INDEX IF NOT EXISTS idx_payments_order ON payments(order_id); CREATE INDEX IF NOT EXISTS idx_ledger_seller ON seller_ledger(seller_id, created_at DESC);
